### ISSUE TITLE
Test Results

### ISSUE THREAD

**Issue by valentinacupac** [jmgarridopaz/bluezone#2]
I have executed the instructions in README for running the project. My next question is - where can I see the test report (i.e., showing tests passing/failing). Thanks in advance!

**Comment by HexArchBook** [comment]
**"ForParkingCars" port tests:**

I use Cucumber. It generates an URL with the report that looks like this:

https://reports.cucumber.io/reports/d8b5cadb-5625-4ac0-a06b-5ed9e0f0ddcb

The long uuid changes for each execution.

The concrete URL of your execution is output in the console when you run the script "run_bluezone.sh":

![cucumber_report](https://user-images.githubusercontent.com/118590249/226028511-b3b4e918-9c00-420d-b1d1-f3b3c4c6762f.png)

**"ForCheckingCars" port tests:**

I use TestNG. It generates reports at the following folder in the computer where you run the script:

<path_to_the_current_user_home_directory>/.testng/reports

For example: /home/jmgarrido/.testng/reports

It is said in the output console when you run the script "run_bluezone.sh":

![testng_output](https://user-images.githubusercontent.com/118590249/226035258-8f9cb27f-0240-4a9e-aa35-d05d07292592.png)


In that folder you can open either the file "index.html" or "emailable-report.html". They are both tests reports of the same execution, but presenting results in different formats.

![testng_folder](https://user-images.githubusercontent.com/118590249/226044011-21e3c8f4-3f7a-45f4-a916-5f99861a2d93.png)

**Comment by jmgarridopaz** [comment]
**"ForParkingCars" port tests:**

I use Cucumber. It generates an URL with the report that looks like this:

https://reports.cucumber.io/reports/d8b5cadb-5625-4ac0-a06b-5ed9e0f0ddcb

The long uuid changes for each execution.

The concrete URL of your execution is output in the console when you run the script "run_bluezone.sh":

![cucumber_report](https://user-images.githubusercontent.com/118590249/226028511-b3b4e918-9c00-420d-b1d1-f3b3c4c6762f.png)

**"ForCheckingCars" port tests:**

I use TestNG. It generates reports at the following folder in the computer where you run the script:

<path_to_the_current_user_home_directory>/.testng/reports

For example: /home/jmgarrido/.testng/reports

It is said in the output console when you run the script "run_bluezone.sh":

![testng_output](https://user-images.githubusercontent.com/118590249/226035258-8f9cb27f-0240-4a9e-aa35-d05d07292592.png)


In that folder you can open either the file "index.html" or "emailable-report.html". They are both tests reports of the same execution, but presenting results in different formats.

![testng_folder](https://user-images.githubusercontent.com/118590249/226044011-21e3c8f4-3f7a-45f4-a916-5f99861a2d93.png)

**Comment by valentinacupac** [comment]
I am using IntelliJ, I have the plugins: Gherkin & Cucumber.

I tried to run "ForParkingCars Test" by going to Maven -> "BlueZone - ForParkingCars Test Driver" -> Lifecycle -> Test

![image](https://user-images.githubusercontent.com/677159/227241092-cd6f5a7a-2c47-45ab-8309-f88e33e8af44.png)

The output I receive is:

![image](https://user-images.githubusercontent.com/677159/227241394-96965e9c-da8d-48f3-9291-a290570328e0.png)

Perhaps I am running something wrong, so if you could let me know which commands you're using on the terminal, or on IDE UI...

**Comment by jmgarridopaz** [comment]
I don't integrate the tests in the maven life cycle. I program the tests as any other drivers. They are modules on its own, they are not on the "test" folder of the project they are testing, they are not run in the test phase of maven.

I haven't seen anybody doing this like I do. People put tests in the test folder of the hexagon. Me not, my understanding of Hexagonal Architecture is to treat tests as any other driving program that uses the hexagon, they uses it for testing its behavior.

So I launch tests from the startup module (main method of BlueZoneRunner class), configuring the "ports-adapters.properties" file (which is an arg of main), located at the "scripts" folder:

![pa_file](https://user-images.githubusercontent.com/44113936/227338093-28e444ae-ac48-4405-8c33-64b685cfcb4e.png)

I run it from the command line of the operating system (not from the IDE), launching the scripts following the instructions on readme file:

![run_instructions](https://user-images.githubusercontent.com/44113936/227339635-ae1d101d-f803-44f0-8307-3b01d94c62c7.png)

The "build.sh" script runs maven to compile, package, and copy the java 9 modules to a module path.

The "run_bluezone.sh" script launches java (with the module path previously built) for running BlueZoneRunner class (with the  "ports-adapters.properties" file as an arg). This class runs the drivers configured in the file, using the driven adapters configured in the file also.

**Comment by valentinacupac** [comment]
Thanks for the explanation; it works now.
